import type { Metadata } from "next";
import { Varela_Round, Lora } from 'next/font/google';

import '@/app/typography-js-copy-paste.css';
import 'prism-solarized-dark/prism-solarizeddark.css'
import '@/app/solarizeddark.css';
import '@/app/style.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const varelaRound = Varela_Round({
  subsets: ['latin'],
  variable: '--font-varela-round',
  weight: '400',
})

const lora = Lora({
  subsets: ['latin-ext'],
  variable: '--font-lora',
  weight: ['400', '600'],
  style: ['normal', 'italic'],
});

/**
 * TODO: Implement Typography.js or equivalent prior to migrating
 * 
 * @see https://share.google/aimode/Nq3i59jFGSaTSWW60
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${varelaRound.variable} ${lora.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
